baseURL = 'https://urfit.nu/'
languageCode = 'nl-nl'
title = 'URfit'
headerLogo = '/images/logo 3 - witte letters - transparant.svg'
theme = 'massively'
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
defaultContentLanguage = "nl"


# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"
  # backgroundPath = "images/bg.jpg"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false
 
 [permalinks]
  posts = '/:filename'

[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true
  
[languages]
[languages.nl]
  languageName = "Nederlands"
  title = "URfit"
#[languages.li]
#  languageName = "Limburgs"
#  title = "URfit"
