name = "URfit"
license = "Creative Commons"
licenselink = "https://github.com/vavdb/hugo-theme-urfit/blob/master/LICENSE"
description = "An elegant open-source and mobile-first theme"
homepage = "https://urfit.nu"
tags = ["blog", "html5up"]
features = ["blog"]
min_version = "0.54.0"

[author]
    name = "Vincent van den Braken"
    homepage = "https://vincent.vandenbraken.com/"

# If porting an existing theme
[original]
    author = "HTML5UP"
    homepage = "https://html5up.net"
    repo = "https://html5up.net/massively"